class_name Routes
extends RefCounted
## Central list of scene paths so transitions are typo-proof.

const TITLE := "res://scenes/ui/TitleScreen.tscn"
const SAVE_SELECT := "res://scenes/ui/SaveSlotMenu.tscn"
const SETTINGS := "res://scenes/ui/SettingsMenu.tscn"
const CHARACTER_CREATION := "res://scenes/ui/CharacterCreation.tscn"
const STARTER_CHOICE := "res://scenes/ui/StarterChoice.tscn"
const OVERWORLD := "res://scenes/world/Overworld.tscn"
const BATTLE := "res://scenes/battle/Battle.tscn"
const REMAP := "res://scenes/ui/RemapMenu.tscn"
const EMBER_TOWN := "res://scenes/world/maps/EmberTownMap.tscn"
const ROUTE_01 := "res://scenes/world/maps/Route01Map.tscn"
const SPROUT_TOWN := "res://scenes/world/maps/SproutTownMap.tscn"
const TIDE_TOWN := "res://scenes/world/maps/TideTownMap.tscn"
const VOLT_TOWN := "res://scenes/world/maps/VoltTownMap.tscn"
const BEDROCK_TOWN := "res://scenes/world/maps/BedrockTownMap.tscn"
const VERDANT_TOWN := "res://scenes/world/maps/VerdantTownMap.tscn"
const LUMEN_TOWN := "res://scenes/world/maps/LumenTownMap.tscn"
const UMBRA_TOWN := "res://scenes/world/maps/UmbraTownMap.tscn"
const NOVA_TOWN := "res://scenes/world/maps/NovaTownMap.tscn"
const ROUTE_SPROUT_EMBER := "res://scenes/world/maps/RouteSproutEmber.tscn"
const ROUTE_TO_TIDE := "res://scenes/world/maps/RouteToTide.tscn"
const ROUTE_TO_VOLT := "res://scenes/world/maps/RouteToVolt.tscn"
const ROUTE_TO_BEDROCK := "res://scenes/world/maps/RouteToBedrock.tscn"
const ROUTE_TO_VERDANT := "res://scenes/world/maps/RouteToVerdant.tscn"
const ROUTE_TO_LUMEN := "res://scenes/world/maps/RouteToLumen.tscn"
const ROUTE_TO_UMBRA := "res://scenes/world/maps/RouteToUmbra.tscn"
const ROUTE_TO_NOVA := "res://scenes/world/maps/RouteToNova.tscn"
